- name: Deploy Vue.js Application
  hosts: deploy
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker Service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add ec2-user to Docker group
      command: usermod -aG docker ec2-user

    - name: Pull latest Docker image
      command: docker pull daiarobert/vue-app:latest

    - name: Stop existing container
      command: docker stop vue-app || true

    - name: Remove existing container
      command: docker rm vue-app || true

    - name: Run new Vue.js container
      command: docker run -d -p 80:80 --name vue-app daiarobert/vue-app:latest
