- name: Deploy Vue.js Application
  hosts: deploy
  become: yes
  tasks:
    - name: Update system packages
      yum:
        name: "*"
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker Service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add ec2-user to Docker group
      command: usermod -aG docker ec2-user

    - name: Restart SSH session to apply group changes
      debug:
        msg: "Please log out and log back in for Docker group changes to take effect."

    - name: Pull latest Docker image
      command: docker pull daiarobert/vue-app:latest

    - name: Check if container is running
      shell: docker ps -q -f name=vue-app
      register: running_container

    - name: Stop existing container (if running)
      command: docker stop vue-app
      when: running_container.stdout != ""
      ignore_errors: yes

    - name: Remove existing container (if exists)
      command: docker rm vue-app
      when: running_container.stdout != ""
      ignore_errors: yes

    - name: Run new Vue.js container
      command: docker run -d -p 8080:80 --name vue-app daiarobert/vue-app:latest
#
