name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main # Rulează workflow-ul doar când faci push pe branch-ul principal

jobs:
  build:
    runs-on: ubuntu-latest # Rulează pipeline-ul pe un server GitHub Actions
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 # Ia codul sursă din repo

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t daiarobert/vue-app:latest .

      - name: Push Docker image
        run: docker push daiarobert/vue-app:latest

      - name: Trigger Jenkins Deployment
        run: |
          curl -u "robert:${{ secrets.JENKINS_API_TOKEN }}" -X POST \
          "http://${{ secrets.JENKINS_URL }}/job/deploy-django/build?token=${{ secrets.JENKINS_TRIGGER_TOKEN }}"
